language: r
sudo: required
cache: packages
warnings_are_errors: true
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran-5
            - gcc-5
            - g++-5
    - os: osx

# Settings to mimic CRAN build
# Modified from github.com/jeroen/jsonlite
osx_image: xcode9

r_packages:
  - Rcpp
  - RcppArmadillo
  - ggplot2
  - tidygraph
  - ggraph
  - glmnet
  - grpreg
  - covr

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++; fi
  - gcc --version
  - g++ --version
  - Rscript -e "source('build_steps.R'); before_install()"

after_success:
  - Rscript -e "source('build_steps.R'); after_success(); unlink('build_steps.R')"
  - Rscript -e 'if(Sys.info()["sysname"] != "Linux"){q()}; library(covr); codecov(quiet=FALSE)'

branches:
  except:
    - master # Don't build "build" branch or else we get in an infinite loop

r_build_args: --no-manual --no-resave-data
r_check_args: --no-manual

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: develop
  local_dir: .
  target_branch: master
  condition: $TRAVIS_OS_NAME = "linux"
