`%||%` <- function(x, y){
  if( (!is.null(x)) && (nzchar(x)) ){
    x
  } else {
    y
  }
}

before_install <- function(){
  ## Build various bits of autogenerated code
  cat("INSTALLING BUILD DEPENDENCIES -------- \n\n")
  for(pkg in c("devtools", "roxygen2", "testthat", "rmarkdown", "pkgdown")){
    if(!require(pkg, character.only=TRUE)){
      install.packages(pkg)
    }
  }
  cat("INSTALLING RUN DEPENDENCIES -------- \n\n")
  devtools::install_deps(dependencies=TRUE, quiet=FALSE, upgrade=FALSE,
                         auth_token = Sys.getenv("GITHUB_PAT") %||% devtools::github_pat(FALSE))

  cat("INSTALLING TEST DEPENDENCIES -------- \n\n")
  for(pkg in c("cmvnorm")){
    if(!require(pkg, character.only=TRUE)){
      install.packages(pkg)
    }
  }

  cat("BUILDING NAMESPACE with roxygen2 -------- \n\n")
  ## Some versions of roxygen2 seem to call Rcpp::compileAttributes which,
  ## in turn, already expects a NAMESPACE file to exists.
  ##
  ## To break the loop, let's write a stub NAMESPACE
  writeLines("# Generated by roxygen2: do not edit by hand\n\nuseDynLib(classo)",
             con="NAMESPACE");
  roxygen2::roxygenize()
  cat("COMPILING RCPP ATTRIBUTES -------- \n\n")
  Rcpp::compileAttributes(verbose=TRUE)
  cat("WRITING DOCUMENTATION -------- \n\n")
  # Shell out to devtools::document to avoid weird reload error
  system("Rscript -e 'devtools::document()'")

  ## Write test stubs to avoid TravisCI time outs when running "coverage version"
  cat("WRITING TEST STUBS -------- \n\n")
  skeleton <- readLines(file.path("tests", "test_stub.R"))
  for(f in list.files(file.path("tests", "testthat"), pattern="test_")){
    stub <- gsub("test_(.*)\\.R", "\\1", f)
    writeLines(gsub("PATTERN", stub, skeleton),
               file.path("tests", paste0("test_", stub, ".R")))
  }
  unlink(file.path("tests", "test_stub.R"))

  ## GitHash for debugging purposes
  cat("ADDING GIT HASH -------- \n\n")
  if(!dir.exists("inst")){
    dir.create("inst")
  }
  writeLines(system("git rev-parse HEAD", intern=TRUE), "inst/GIT.HASH")
}

after_success <- function(){
  devtools::install(reload = TRUE, quick = TRUE, quiet = FALSE, upgrade = FALSE,
                    auth_token = Sys.getenv("GITHUB_TOKEN") %||% devtools::github_pat(FALSE))
  rmarkdown::render("README.Rmd", clean = FALSE)
  unlink("README.knit.md", force = TRUE)
  unlink("README.utf8.md", force = TRUE)

  ## Build pkgdown site
  pkgdown::build_site()

  ## Clean up build artifacts
  unlink(Sys.glob("classo.Rcheck"), recursive=TRUE, force=TRUE)
  unlink(Sys.glob("classo*.tar.gz"), recursive=TRUE, force=TRUE)
  file.rename(".gitignore.deploy", ".gitignore")
  unlink(Sys.glob("src/*o"), force=TRUE)
}
